import tempfile
from fpdf import FPDF
from stp.core.pipeline import AnalysisResult

class SystemicTauPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Systemic Tau Platform - Scientific Report', 0, 1, 'C')
        self.set_draw_color(0, 80, 180)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(result: AnalysisResult, domain: str = "synthetic") -> bytes:
    pdf = SystemicTauPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f'Analysis Domain: {domain.upper()}', 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 10, f'Reproducibility Hash: {result.repro_hash}', 0, 1)
    pdf.ln(5)
    
    # Parameters
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Parameters', 0, 1)
    pdf.set_font('Arial', '', 12)
    p = result.params
    pdf.cell(0, 8, f'- Window: {p.window} | Stride: {p.stride} | m: {p.m} | Delay: {p.delay}', 0, 1)
    pdf.cell(0, 8, f'- Theta3: {p.theta3} | Mode: {p.mode}', 0, 1)
    pdf.ln(5)
    
    # Metrics
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Core Metrics', 0, 1)
    pdf.set_font('Arial', '', 12)
    
    metrics = result.metrics
    pdf.cell(0, 8, f"- Mean Tau_s: {metrics.get('mean_tau_s', 0):.4f}", 0, 1)
    pdf.cell(0, 8, f"- Delta Tau_s: {metrics.get('delta_tau_s', 0):.4f}", 0, 1)
    pdf.cell(0, 8, f"- Mean Excess3: {metrics.get('mean_excess3', 0):.4f}", 0, 1)
    pdf.cell(0, 8, f"- Delta Excess3: {metrics.get('delta_excess3', 0):.4f}", 0, 1)
    pdf.cell(0, 8, f"- Final T_recd: {metrics.get('final_T_recd', 0):.4f}", 0, 1)
    
    pval = result.surrogate_stats.get("tau_s", {}).get("p_value", None)
    if pval is not None:
        pdf.cell(0, 8, f"- Surrogate p-value: {pval:.4f}", 0, 1)
        
    pdf.ln(10)
    
    # Theory / Glossary
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Theoretical Interpretation', 0, 1)
    pdf.set_font('Arial', '', 11)
    
    theory_text = (
        "Systemic Tau measures the temporal and topological synchronization of a complex system. "
        "Values near 1 indicate strong topological persistence (Phase 1). "
        "Values near 0 indicate high entropy or dissonance (Phase 2). "
        "Values near -1 indicate anti-synchronization. "
        "The RECD (Reloj Extramental Discreto) accumulates discrete state changes, tracking the true 'systemic time' "
        "rather than chronological time."
    )
    pdf.multi_cell(0, 6, theory_text)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 10, 'Generated by Systemic Tau Platform v1.1.0 (Python fpdf2)', 0, 1)
    
    # Output to bytes
    return pdf.output(dest="S").encode('latin-1')
